tasks:
  - name: "maxCompute"
    schedule: "* * * * *"
    cookie:
      method: "chromedp"
      update_interval: "24h"
    request:
      url: "https://example.com/"
      method: "GET"
      headers:
        Content-Type: "application/json"
    storage:
      type: "database"
      connection: "db_connection_string"
      replace_old: true
  - name: "test test"
    schedule: "*/2 * * * *"
    cookie:
      method: "chromedp"
      update_interval: "24h"
    request:
      url: "https://example.com/"
      method: "GET"
      headers:
        Content-Type: "application/json"
    storage:
      type: "database"
      connection: "db_connection_string"
      replace_old: true
